"""Add CalibreReadingProgress model

Revision ID: 503379c80f43
Revises: eaecc71f5608
Create Date: 2025-11-30 14:39:31.729600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503379c80f43'
down_revision = 'eaecc71f5608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibre_reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ebook_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('last_read', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ebook_id', name='_user_calibre_ebook_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calibre_reading_progress')
    # ### end Alembic commands ###
